
# VMA C++ wrapper - compiled as C++ since VMA is a C++ header-only library
./src/backends/vulkan/vio_vma_wrapper.lo: /Users/hendrikmennen/Projekte/php-vio/src/backends/vulkan/vio_vma_wrapper.cpp
	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) -std=c++14 \
		-I/Users/hendrikmennen/Projekte/php-vio/vendor/vma -I/Users/hendrikmennen/Projekte/php-vio/include -I. \
		-DHAVE_CONFIG_H -fPIC -O2 \
		-c /Users/hendrikmennen/Projekte/php-vio/src/backends/vulkan/vio_vma_wrapper.cpp \
		-o ./src/backends/vulkan/vio_vma_wrapper.lo

# Add VMA wrapper to the shared object list
shared_objects_vio += src/backends/vulkan/vio_vma_wrapper.lo

# Metal backend - compiled as Objective-C
./src/backends/metal/vio_metal.lo: /Users/hendrikmennen/Projekte/php-vio/src/backends/metal/vio_metal.m
	@mkdir -p ./src/backends/metal
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -x objective-c \
		$(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) \
		-I$(top_srcdir) -I$(top_builddir) \
		-I/Users/hendrikmennen/Projekte/php-vio/include -I. \
		$(INCLUDES) \
		-DHAVE_CONFIG_H -fPIC -O2 \
		-fobjc-arc \
		-c /Users/hendrikmennen/Projekte/php-vio/src/backends/metal/vio_metal.m \
		-o ./src/backends/metal/vio_metal.lo

shared_objects_vio += src/backends/metal/vio_metal.lo
