/*
 * php-vio - Wayland platform (NATIVE-PLATFORM-PLAN Phase 3, OPEN-ITEMS A3)
 *
 * Linux on a Wayland compositor without GLFW or XWayland: xdg-shell
 * toplevels (server-side decorations through xdg-decoration where the
 * compositor offers them), keys by evdev keycode (the physical position, as
 * the Win32 scancodes and the X11 key names) with text, modifiers and the
 * compositor's repeat rate through xkbcommon, pointer buttons and wheels, a
 * locked pointer with relative motion for VIO_CURSOR_DISABLED, the cursor
 * theme's arrow through wayland-cursor, outputs as monitors (fullscreen on
 * an output - Wayland has no mode switch, the compositor scales), integer
 * buffer scale from the outputs the surface is on, evdev gamepads (shared
 * with X11), the Vulkan Wayland surface, and OpenGL through EGL on a
 * wl_egl_window - libEGL and libwayland-egl are opened at run time.
 *
 * The protocol glue for xdg-shell, xdg-decoration, relative-pointer and
 * pointer-constraints is generated by wayland-scanner at configure time
 * into gen/ (config.m4) and compiled into this translation unit.
 *
 * Chosen over X11 when WAYLAND_DISPLAY is set (src/vio_platform_registry.c),
 * as GLFW 3.4 does; VIO_PLATFORM=x11 picks XWayland instead. A Wayland
 * client cannot read or set its window position (always 0, 0), and a window
 * is only mapped once it has drawn - headless contexts are mapped too, or the
 * compositor would never send the frame callbacks a vsync'd present waits for.
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"

#ifdef HAVE_WAYLAND

#include <wayland-client.h>
#include <wayland-cursor.h>
#include <xkbcommon/xkbcommon.h>
#include <dlfcn.h>
#include <poll.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <time.h>
#include <unistd.h>

#include "gen/xdg-shell-client-protocol.h"
#include "gen/xdg-decoration-unstable-v1-client-protocol.h"
#include "gen/relative-pointer-unstable-v1-client-protocol.h"
#include "gen/pointer-constraints-unstable-v1-client-protocol.h"
#include "gen/xdg-shell-protocol.c"
#include "gen/xdg-decoration-unstable-v1-protocol.c"
#include "gen/relative-pointer-unstable-v1-protocol.c"
#include "gen/pointer-constraints-unstable-v1-protocol.c"

#ifdef HAVE_VULKAN
#define VK_USE_PLATFORM_WAYLAND_KHR
#include <vulkan/vulkan.h>
#endif

#include "../../../include/vio_platform.h"
#include "../../../include/vio_constants.h"
#include "../../vio_input.h"
#include "../linux/vio_evdev_gamepad.h"

typedef struct _vio_wl_window vio_wl_window;

/* ── Globals ──────────────────────────────────────────────────────── */

#define WL_MAX_OUTPUTS 16
#define WL_MAX_MODES   32

typedef struct {
    struct wl_output *output;
    uint32_t          id;
    int               x, y;
    int               width, height, refresh_mhz;   /* current mode */
    int               scale;
    char              name[128];
    vio_video_mode    modes[WL_MAX_MODES];
    int               mode_n;
} wl_output_info;

static struct {
    struct wl_display    *display;
    struct wl_registry   *registry;
    struct wl_compositor *compositor;
    struct wl_shm        *shm;
    struct xdg_wm_base   *wm_base;
    struct wl_seat       *seat;
    struct wl_keyboard   *keyboard;
    struct wl_pointer    *pointer;
    struct zxdg_decoration_manager_v1        *decoration_manager;
    struct zwp_relative_pointer_manager_v1   *relative_manager;
    struct zwp_pointer_constraints_v1        *constraints;
    struct wl_cursor_theme *cursor_theme;
    struct wl_cursor       *cursor;
    struct wl_surface      *cursor_surface;
    wl_output_info          outputs[WL_MAX_OUTPUTS];
    int                     output_n;
    struct xkb_context *xkb;
    struct xkb_keymap  *keymap;
    struct xkb_state   *xkb_state;
    vio_wl_window      *keyboard_focus;
    vio_wl_window      *pointer_focus;
    uint32_t            pointer_serial;
    int                 repeat_rate, repeat_delay;   /* keys/s, ms */
    uint32_t            repeat_key;                  /* evdev code + 1, 0 = none */
    double              repeat_next;
    int                 initialized;
} wl;

/* ── Window state ─────────────────────────────────────────────────── */

struct _vio_wl_window {
    struct wl_surface   *surface;
    struct xdg_surface  *xdg_surface;
    struct xdg_toplevel *toplevel;
    struct zxdg_toplevel_decoration_v1 *decoration;
    struct zwp_locked_pointer_v1   *locked;
    struct zwp_relative_pointer_v1 *relative;
    void                *egl_window;    /* struct wl_egl_window * */
    void                *egl_surface;
    void                *egl_context;
    int                  configured;
    int                  width, height;  /* logical */
    int                  scale;
    int                  should_close;
    int                  headless;
    int                  decorated;
    int                  auto_iconify;
    int                  maximized;
    int                  cursor_mode;
    double               cursor_x, cursor_y;
    int                  monitor;
    int                  on_output[WL_MAX_OUTPUTS];
    int                  fb_w, fb_h;
    vio_input_state     *input;
};

static vio_input_state *wl_input(vio_wl_window *w)
{
    return (w && w->input && !w->input->replaying) ? w->input : NULL;
}

static double wl_now(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec + (double)ts.tv_nsec * 1e-9;
}

/* ── EGL + wayland-egl (run time) ─────────────────────────────────── */

typedef int32_t EGLint_;
typedef void *(*wl_egl_window_create_t)(struct wl_surface *, int, int);
typedef void  (*wl_egl_window_resize_t)(void *, int, int, int, int);
typedef void  (*wl_egl_window_destroy_t)(void *);

static void *wl_libegl, *wl_libwegl, *wl_libgl;
static void *wl_egl_display;
static struct {
    void *(*GetDisplay)(void *);
    unsigned (*Initialize)(void *, EGLint_ *, EGLint_ *);
    unsigned (*BindAPI)(unsigned);
    unsigned (*ChooseConfig)(void *, const EGLint_ *, void **, EGLint_, EGLint_ *);
    void *(*CreateContext)(void *, void *, void *, const EGLint_ *);
    void *(*CreateWindowSurface)(void *, void *, void *, const EGLint_ *);
    unsigned (*MakeCurrent)(void *, void *, void *, void *);
    unsigned (*SwapBuffers)(void *, void *);
    unsigned (*SwapInterval)(void *, EGLint_);
    unsigned (*DestroySurface)(void *, void *);
    unsigned (*DestroyContext)(void *, void *);
    void *(*GetProcAddress)(const char *);
    void *(*GetCurrentContext)(void);
    wl_egl_window_create_t  window_create;
    wl_egl_window_resize_t  window_resize;
    wl_egl_window_destroy_t window_destroy;
} egl;

#define WL_EGL_SURFACE_TYPE      0x3033
#define WL_EGL_WINDOW_BIT        0x0004
#define WL_EGL_RENDERABLE_TYPE   0x3040
#define WL_EGL_OPENGL_BIT        0x0008
#define WL_EGL_RED_SIZE          0x3024
#define WL_EGL_GREEN_SIZE        0x3023
#define WL_EGL_BLUE_SIZE         0x3022
#define WL_EGL_ALPHA_SIZE        0x3021
#define WL_EGL_DEPTH_SIZE        0x3025
#define WL_EGL_STENCIL_SIZE      0x3026
#define WL_EGL_SAMPLE_BUFFERS    0x3032
#define WL_EGL_SAMPLES           0x3031
#define WL_EGL_NONE              0x3038
#define WL_EGL_OPENGL_API        0x30A2
#define WL_EGL_CONTEXT_MAJOR     0x3098
#define WL_EGL_CONTEXT_MINOR     0x30FB
#define WL_EGL_CONTEXT_PROFILE   0x30FD
#define WL_EGL_CONTEXT_CORE_BIT  0x0001

static int wl_egl_load(void)
{
    if (wl_egl_display) return 1;
    if (!wl_libegl) wl_libegl = dlopen("libEGL.so.1", RTLD_LAZY | RTLD_GLOBAL);
    if (!wl_libwegl) wl_libwegl = dlopen("libwayland-egl.so.1", RTLD_LAZY | RTLD_GLOBAL);
    if (!wl_libegl || !wl_libwegl) return 0;
#define WL_EGL_SYM(field, name) *(void **)&egl.field = dlsym(wl_libegl, name)
    WL_EGL_SYM(GetDisplay, "eglGetDisplay");
    WL_EGL_SYM(Initialize, "eglInitialize");
    WL_EGL_SYM(BindAPI, "eglBindAPI");
    WL_EGL_SYM(ChooseConfig, "eglChooseConfig");
    WL_EGL_SYM(CreateContext, "eglCreateContext");
    WL_EGL_SYM(CreateWindowSurface, "eglCreateWindowSurface");
    WL_EGL_SYM(MakeCurrent, "eglMakeCurrent");
    WL_EGL_SYM(SwapBuffers, "eglSwapBuffers");
    WL_EGL_SYM(SwapInterval, "eglSwapInterval");
    WL_EGL_SYM(DestroySurface, "eglDestroySurface");
    WL_EGL_SYM(DestroyContext, "eglDestroyContext");
    WL_EGL_SYM(GetProcAddress, "eglGetProcAddress");
    WL_EGL_SYM(GetCurrentContext, "eglGetCurrentContext");
#undef WL_EGL_SYM
    egl.window_create  = (wl_egl_window_create_t)dlsym(wl_libwegl, "wl_egl_window_create");
    egl.window_resize  = (wl_egl_window_resize_t)dlsym(wl_libwegl, "wl_egl_window_resize");
    egl.window_destroy = (wl_egl_window_destroy_t)dlsym(wl_libwegl, "wl_egl_window_destroy");
    if (!egl.GetDisplay || !egl.Initialize || !egl.BindAPI || !egl.ChooseConfig || !egl.CreateContext
        || !egl.CreateWindowSurface || !egl.MakeCurrent || !egl.SwapBuffers || !egl.GetProcAddress
        || !egl.window_create || !egl.window_resize || !egl.window_destroy) return 0;
    void *d = egl.GetDisplay(wl.display);
    EGLint_ major = 0, minor = 0;
    if (!d || !egl.Initialize(d, &major, &minor)) return 0;
    wl_egl_display = d;
    return 1;
}

static void *wl_gl_get_proc_address(const char *name)
{
    void *p = (wl_egl_display && egl.GetProcAddress) ? egl.GetProcAddress(name) : NULL;
    if (p) return p;
    if (!wl_libgl) wl_libgl = dlopen("libOpenGL.so.0", RTLD_LAZY | RTLD_GLOBAL);
    if (!wl_libgl) wl_libgl = dlopen("libGL.so.1", RTLD_LAZY | RTLD_GLOBAL);
    return wl_libgl ? dlsym(wl_libgl, name) : NULL;
}

/* ── Keyboard: evdev keycode -> VIO_KEY_* ─────────────────────────── */

static int wl_key(uint32_t code)
{
    static const struct { uint16_t code; int16_t key; } t[] = {
        {KEY_GRAVE, VIO_KEY_GRAVE_ACCENT}, {KEY_1, VIO_KEY_1}, {KEY_2, VIO_KEY_2}, {KEY_3, VIO_KEY_3}, {KEY_4, VIO_KEY_4},
        {KEY_5, VIO_KEY_5}, {KEY_6, VIO_KEY_6}, {KEY_7, VIO_KEY_7}, {KEY_8, VIO_KEY_8}, {KEY_9, VIO_KEY_9},
        {KEY_0, VIO_KEY_0}, {KEY_MINUS, VIO_KEY_MINUS}, {KEY_EQUAL, VIO_KEY_EQUAL},
        {KEY_Q, VIO_KEY_Q}, {KEY_W, VIO_KEY_W}, {KEY_E, VIO_KEY_E}, {KEY_R, VIO_KEY_R}, {KEY_T, VIO_KEY_T},
        {KEY_Y, VIO_KEY_Y}, {KEY_U, VIO_KEY_U}, {KEY_I, VIO_KEY_I}, {KEY_O, VIO_KEY_O}, {KEY_P, VIO_KEY_P},
        {KEY_LEFTBRACE, VIO_KEY_LEFT_BRACKET}, {KEY_RIGHTBRACE, VIO_KEY_RIGHT_BRACKET},
        {KEY_A, VIO_KEY_A}, {KEY_S, VIO_KEY_S}, {KEY_D, VIO_KEY_D}, {KEY_F, VIO_KEY_F}, {KEY_G, VIO_KEY_G},
        {KEY_H, VIO_KEY_H}, {KEY_J, VIO_KEY_J}, {KEY_K, VIO_KEY_K}, {KEY_L, VIO_KEY_L}, {KEY_SEMICOLON, VIO_KEY_SEMICOLON},
        {KEY_APOSTROPHE, VIO_KEY_APOSTROPHE},
        {KEY_Z, VIO_KEY_Z}, {KEY_X, VIO_KEY_X}, {KEY_C, VIO_KEY_C}, {KEY_V, VIO_KEY_V}, {KEY_B, VIO_KEY_B},
        {KEY_N, VIO_KEY_N}, {KEY_M, VIO_KEY_M}, {KEY_COMMA, VIO_KEY_COMMA}, {KEY_DOT, VIO_KEY_PERIOD}, {KEY_SLASH, VIO_KEY_SLASH},
        {KEY_BACKSLASH, VIO_KEY_BACKSLASH}, {KEY_102ND, 162 /* WORLD_2 */},
        {KEY_SPACE, VIO_KEY_SPACE}, {KEY_ESC, VIO_KEY_ESCAPE}, {KEY_ENTER, VIO_KEY_ENTER}, {KEY_TAB, VIO_KEY_TAB},
        {KEY_BACKSPACE, VIO_KEY_BACKSPACE}, {KEY_INSERT, VIO_KEY_INSERT}, {KEY_DELETE, VIO_KEY_DELETE},
        {KEY_RIGHT, VIO_KEY_RIGHT}, {KEY_LEFT, VIO_KEY_LEFT}, {KEY_DOWN, VIO_KEY_DOWN}, {KEY_UP, VIO_KEY_UP},
        {KEY_PAGEUP, VIO_KEY_PAGE_UP}, {KEY_PAGEDOWN, VIO_KEY_PAGE_DOWN}, {KEY_HOME, VIO_KEY_HOME}, {KEY_END, VIO_KEY_END},
        {KEY_CAPSLOCK, VIO_KEY_CAPS_LOCK}, {KEY_SCROLLLOCK, VIO_KEY_SCROLL_LOCK}, {KEY_NUMLOCK, VIO_KEY_NUM_LOCK},
        {KEY_SYSRQ, VIO_KEY_PRINT_SCREEN}, {KEY_PAUSE, VIO_KEY_PAUSE},
        {KEY_F1, VIO_KEY_F1}, {KEY_F2, VIO_KEY_F2}, {KEY_F3, VIO_KEY_F3}, {KEY_F4, VIO_KEY_F4}, {KEY_F5, VIO_KEY_F5},
        {KEY_F6, VIO_KEY_F6}, {KEY_F7, VIO_KEY_F7}, {KEY_F8, VIO_KEY_F8}, {KEY_F9, VIO_KEY_F9}, {KEY_F10, VIO_KEY_F10},
        {KEY_F11, VIO_KEY_F11}, {KEY_F12, VIO_KEY_F12}, {KEY_F13, 302}, {KEY_F14, 303}, {KEY_F15, 304}, {KEY_F16, 305},
        {KEY_F17, 306}, {KEY_F18, 307}, {KEY_F19, 308}, {KEY_F20, 309}, {KEY_F21, 310}, {KEY_F22, 311}, {KEY_F23, 312},
        {KEY_F24, 313},
        {KEY_KP0, VIO_KEY_KP_0}, {KEY_KP1, VIO_KEY_KP_1}, {KEY_KP2, VIO_KEY_KP_2}, {KEY_KP3, VIO_KEY_KP_3},
        {KEY_KP4, VIO_KEY_KP_4}, {KEY_KP5, VIO_KEY_KP_5}, {KEY_KP6, VIO_KEY_KP_6}, {KEY_KP7, VIO_KEY_KP_7},
        {KEY_KP8, VIO_KEY_KP_8}, {KEY_KP9, VIO_KEY_KP_9}, {KEY_KPDOT, VIO_KEY_KP_DECIMAL}, {KEY_KPSLASH, VIO_KEY_KP_DIVIDE},
        {KEY_KPASTERISK, VIO_KEY_KP_MULTIPLY}, {KEY_KPMINUS, VIO_KEY_KP_SUBTRACT}, {KEY_KPPLUS, VIO_KEY_KP_ADD},
        {KEY_KPENTER, VIO_KEY_KP_ENTER}, {KEY_KPEQUAL, VIO_KEY_KP_EQUAL},
        {KEY_LEFTSHIFT, VIO_KEY_LEFT_SHIFT}, {KEY_LEFTCTRL, VIO_KEY_LEFT_CONTROL}, {KEY_LEFTALT, VIO_KEY_LEFT_ALT},
        {KEY_LEFTMETA, VIO_KEY_LEFT_SUPER}, {KEY_RIGHTSHIFT, VIO_KEY_RIGHT_SHIFT}, {KEY_RIGHTCTRL, VIO_KEY_RIGHT_CONTROL},
        {KEY_RIGHTALT, VIO_KEY_RIGHT_ALT}, {KEY_RIGHTMETA, VIO_KEY_RIGHT_SUPER}, {KEY_COMPOSE, VIO_KEY_MENU},
        {KEY_MENU, VIO_KEY_MENU},
    };
    for (size_t i = 0; i < sizeof(t) / sizeof(t[0]); i++) if (t[i].code == code) return t[i].key;
    return VIO_KEY_UNKNOWN;
}

static int wl_mods(void)
{
    if (!wl.xkb_state) return 0;
    int m = 0;
    if (xkb_state_mod_name_is_active(wl.xkb_state, XKB_MOD_NAME_SHIFT, XKB_STATE_MODS_EFFECTIVE) > 0) m |= VIO_MOD_SHIFT;
    if (xkb_state_mod_name_is_active(wl.xkb_state, XKB_MOD_NAME_CTRL, XKB_STATE_MODS_EFFECTIVE) > 0)  m |= VIO_MOD_CONTROL;
    if (xkb_state_mod_name_is_active(wl.xkb_state, XKB_MOD_NAME_ALT, XKB_STATE_MODS_EFFECTIVE) > 0)   m |= VIO_MOD_ALT;
    if (xkb_state_mod_name_is_active(wl.xkb_state, XKB_MOD_NAME_LOGO, XKB_STATE_MODS_EFFECTIVE) > 0)  m |= VIO_MOD_SUPER;
    if (xkb_state_mod_name_is_active(wl.xkb_state, XKB_MOD_NAME_CAPS, XKB_STATE_MODS_EFFECTIVE) > 0)  m |= VIO_MOD_CAPS_LOCK;
    if (xkb_state_mod_name_is_active(wl.xkb_state, XKB_MOD_NAME_NUM, XKB_STATE_MODS_EFFECTIVE) > 0)   m |= VIO_MOD_NUM_LOCK;
    return m;
}

/* Key event plus the text it types (repeats type again). */
static void wl_emit_key(vio_wl_window *w, uint32_t code, int action)
{
    vio_input_key_event(wl_input(w), wl_key(code), action, wl_mods());
    if (action == VIO_RELEASE || !wl.xkb_state) return;
    uint32_t cp = xkb_state_key_get_utf32(wl.xkb_state, code + 8);
    if (cp >= 32 && cp != 127 && !(cp >= 0x80 && cp < 0xA0)) vio_input_emit_char(wl_input(w), cp);
}

/* ── Scale, size ──────────────────────────────────────────────────── */

static int wl_window_scale(vio_wl_window *w)
{
    if (w->headless) return 1;   /* headless surfaces are exactly the requested pixels */
    int s = 1;
    for (int i = 0; i < wl.output_n; i++) if (w->on_output[i] && wl.outputs[i].scale > s) s = wl.outputs[i].scale;
    return s;
}

static void wl_apply_size(vio_wl_window *w)
{
    int scale = wl_window_scale(w);
    if (scale != w->scale) {
        w->scale = scale;
        wl_surface_set_buffer_scale(w->surface, scale);
    }
    int fw = w->width * scale, fh = w->height * scale;
    if (w->egl_window) egl.window_resize(w->egl_window, fw, fh, 0, 0);
    if (fw != w->fb_w || fh != w->fb_h) {
        w->fb_w = fw;
        w->fb_h = fh;
        vio_input_resize_event(w->input, fw, fh);
    }
}

/* ── Surface, xdg ─────────────────────────────────────────────────── */

static void wl_surface_enter(void *data, struct wl_surface *s, struct wl_output *o)
{
    (void)s;
    vio_wl_window *w = (vio_wl_window *)data;
    for (int i = 0; i < wl.output_n; i++) if (wl.outputs[i].output == o) w->on_output[i] = 1;
    wl_apply_size(w);
}

static void wl_surface_leave(void *data, struct wl_surface *s, struct wl_output *o)
{
    (void)s;
    vio_wl_window *w = (vio_wl_window *)data;
    for (int i = 0; i < wl.output_n; i++) if (wl.outputs[i].output == o) w->on_output[i] = 0;
    wl_apply_size(w);
}

static const struct wl_surface_listener wl_surface_listener = { wl_surface_enter, wl_surface_leave };

static void wl_xdg_surface_configure(void *data, struct xdg_surface *s, uint32_t serial)
{
    vio_wl_window *w = (vio_wl_window *)data;
    xdg_surface_ack_configure(s, serial);
    w->configured = 1;
    wl_apply_size(w);
}

static const struct xdg_surface_listener wl_xdg_surface_listener = { wl_xdg_surface_configure };

static void wl_toplevel_configure(void *data, struct xdg_toplevel *t, int32_t width, int32_t height, struct wl_array *states)
{
    (void)t;
    vio_wl_window *w = (vio_wl_window *)data;
    w->maximized = 0;
    uint32_t *st;
    wl_array_for_each(st, states) if (*st == XDG_TOPLEVEL_STATE_MAXIMIZED) w->maximized = 1;
    if (width > 0 && height > 0) { w->width = width; w->height = height; }   /* 0: the client decides */
}

static void wl_toplevel_close(void *data, struct xdg_toplevel *t)
{
    (void)t;
    ((vio_wl_window *)data)->should_close = 1;
}

/* bound at version 1: configure_bounds / wm_capabilities (v4 / v5) never arrive */
static const struct xdg_toplevel_listener wl_toplevel_listener = { .configure = wl_toplevel_configure, .close = wl_toplevel_close };

static void wl_wm_ping(void *data, struct xdg_wm_base *b, uint32_t serial) { (void)data; xdg_wm_base_pong(b, serial); }
static const struct xdg_wm_base_listener wl_wm_listener = { wl_wm_ping };

static void wl_decoration_configure(void *data, struct zxdg_toplevel_decoration_v1 *d, uint32_t mode) { (void)data; (void)d; (void)mode; }
static const struct zxdg_toplevel_decoration_v1_listener wl_decoration_listener = { wl_decoration_configure };

/* ── Pointer ──────────────────────────────────────────────────────── */

static void wl_set_cursor(vio_wl_window *w)
{
    if (!wl.pointer) return;
    if (!w || w->cursor_mode != VIO_PLATFORM_CURSOR_NORMAL || !wl.cursor || !wl.cursor_surface) {
        wl_pointer_set_cursor(wl.pointer, wl.pointer_serial, NULL, 0, 0);
        return;
    }
    struct wl_cursor_image *img = wl.cursor->images[0];
    struct wl_buffer *buf = wl_cursor_image_get_buffer(img);
    if (!buf) return;
    wl_pointer_set_cursor(wl.pointer, wl.pointer_serial, wl.cursor_surface, (int32_t)img->hotspot_x, (int32_t)img->hotspot_y);
    wl_surface_attach(wl.cursor_surface, buf, 0, 0);
    wl_surface_damage(wl.cursor_surface, 0, 0, (int32_t)img->width, (int32_t)img->height);
    wl_surface_commit(wl.cursor_surface);
}

static void wl_pointer_enter(void *data, struct wl_pointer *p, uint32_t serial, struct wl_surface *s, wl_fixed_t sx, wl_fixed_t sy)
{
    (void)data; (void)p;
    wl.pointer_serial = serial;
    vio_wl_window *w = s ? (vio_wl_window *)wl_surface_get_user_data(s) : NULL;
    wl.pointer_focus = w;
    if (!w) return;
    wl_set_cursor(w);
    if (w->cursor_mode != VIO_PLATFORM_CURSOR_DISABLED) {
        w->cursor_x = wl_fixed_to_double(sx);
        w->cursor_y = wl_fixed_to_double(sy);
        vio_input_cursor_event(wl_input(w), w->cursor_x, w->cursor_y);
    }
}

static void wl_pointer_leave(void *data, struct wl_pointer *p, uint32_t serial, struct wl_surface *s)
{
    (void)data; (void)p; (void)serial; (void)s;
    wl.pointer_focus = NULL;
}

static void wl_pointer_motion(void *data, struct wl_pointer *p, uint32_t time, wl_fixed_t sx, wl_fixed_t sy)
{
    (void)data; (void)p; (void)time;
    vio_wl_window *w = wl.pointer_focus;
    if (!w || w->cursor_mode == VIO_PLATFORM_CURSOR_DISABLED) return;
    w->cursor_x = wl_fixed_to_double(sx);
    w->cursor_y = wl_fixed_to_double(sy);
    vio_input_cursor_event(wl_input(w), w->cursor_x, w->cursor_y);
}

static void wl_pointer_button(void *data, struct wl_pointer *p, uint32_t serial, uint32_t time, uint32_t button, uint32_t state)
{
    (void)data; (void)p; (void)time;
    wl.pointer_serial = serial;
    vio_wl_window *w = wl.pointer_focus;
    if (!w) return;
    int b = button == BTN_LEFT ? 0 : button == BTN_RIGHT ? 1 : button == BTN_MIDDLE ? 2 : (int)(button - BTN_SIDE) + 3;
    if (b < 0 || b > VIO_MOUSE_LAST) return;
    vio_input_button_event(wl_input(w), b, state == WL_POINTER_BUTTON_STATE_PRESSED ? VIO_PRESS : VIO_RELEASE);
}

/* GLFW's factor: one wheel notch (10 units) is 1.0, positive up / left. */
static void wl_pointer_axis(void *data, struct wl_pointer *p, uint32_t time, uint32_t axis, wl_fixed_t value)
{
    (void)data; (void)p; (void)time;
    vio_wl_window *w = wl.pointer_focus;
    if (!w) return;
    double v = -wl_fixed_to_double(value) / 10.0;
    if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL) vio_input_scroll_event(wl_input(w), 0.0, v);
    else vio_input_scroll_event(wl_input(w), v, 0.0);
}

static void wl_pointer_frame(void *data, struct wl_pointer *p) { (void)data; (void)p; }
static void wl_pointer_axis_source(void *data, struct wl_pointer *p, uint32_t s) { (void)data; (void)p; (void)s; }
static void wl_pointer_axis_stop(void *data, struct wl_pointer *p, uint32_t t, uint32_t a) { (void)data; (void)p; (void)t; (void)a; }
static void wl_pointer_axis_discrete(void *data, struct wl_pointer *p, uint32_t a, int32_t d) { (void)data; (void)p; (void)a; (void)d; }

static const struct wl_pointer_listener wl_pointer_listener = {
    wl_pointer_enter, wl_pointer_leave, wl_pointer_motion, wl_pointer_button, wl_pointer_axis,
    wl_pointer_frame, wl_pointer_axis_source, wl_pointer_axis_stop, wl_pointer_axis_discrete,
};

static void wl_relative_motion(void *data, struct zwp_relative_pointer_v1 *r, uint32_t hi, uint32_t lo,
                               wl_fixed_t dx, wl_fixed_t dy, wl_fixed_t dxu, wl_fixed_t dyu)
{
    (void)r; (void)hi; (void)lo; (void)dxu; (void)dyu;
    vio_wl_window *w = (vio_wl_window *)data;
    if (w->cursor_mode != VIO_PLATFORM_CURSOR_DISABLED) return;
    w->cursor_x += wl_fixed_to_double(dx);
    w->cursor_y += wl_fixed_to_double(dy);
    vio_input_cursor_event(wl_input(w), w->cursor_x, w->cursor_y);
}

static const struct zwp_relative_pointer_v1_listener wl_relative_listener = { wl_relative_motion };

static void wl_locked(void *data, struct zwp_locked_pointer_v1 *l) { (void)data; (void)l; }
static void wl_unlocked(void *data, struct zwp_locked_pointer_v1 *l) { (void)data; (void)l; }
static const struct zwp_locked_pointer_v1_listener wl_locked_listener = { wl_locked, wl_unlocked };

/* ── Keyboard ─────────────────────────────────────────────────────── */

static void wl_keyboard_keymap(void *data, struct wl_keyboard *k, uint32_t format, int32_t fd, uint32_t size)
{
    (void)data; (void)k;
    if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1) { close(fd); return; }
    char *map = mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, 0);
    close(fd);
    if (map == MAP_FAILED) return;
    struct xkb_keymap *km = xkb_keymap_new_from_string(wl.xkb, map, XKB_KEYMAP_FORMAT_TEXT_V1, XKB_KEYMAP_COMPILE_NO_FLAGS);
    munmap(map, size);
    if (!km) return;
    struct xkb_state *st = xkb_state_new(km);
    if (!st) { xkb_keymap_unref(km); return; }
    if (wl.xkb_state) xkb_state_unref(wl.xkb_state);
    if (wl.keymap) xkb_keymap_unref(wl.keymap);
    wl.keymap = km;
    wl.xkb_state = st;
}

static void wl_keyboard_enter(void *data, struct wl_keyboard *k, uint32_t serial, struct wl_surface *s, struct wl_array *keys)
{
    (void)data; (void)k; (void)serial; (void)keys;
    wl.keyboard_focus = s ? (vio_wl_window *)wl_surface_get_user_data(s) : NULL;
}

static void wl_keyboard_leave(void *data, struct wl_keyboard *k, uint32_t serial, struct wl_surface *s)
{
    (void)data; (void)k; (void)serial; (void)s;
    vio_wl_window *w = wl.keyboard_focus;
    wl.keyboard_focus = NULL;
    wl.repeat_key = 0;
    if (w && w->monitor >= 0 && w->auto_iconify) xdg_toplevel_set_minimized(w->toplevel);
}

static void wl_keyboard_key(void *data, struct wl_keyboard *k, uint32_t serial, uint32_t time, uint32_t key, uint32_t state)
{
    (void)data; (void)k; (void)serial; (void)time;
    vio_wl_window *w = wl.keyboard_focus;
    if (!w) return;
    int press = state == WL_KEYBOARD_KEY_STATE_PRESSED;
    wl_emit_key(w, key, press ? VIO_PRESS : VIO_RELEASE);
    if (press && wl.repeat_rate > 0 && wl.keymap && xkb_keymap_key_repeats(wl.keymap, key + 8)) {
        wl.repeat_key = key + 1;
        wl.repeat_next = wl_now() + wl.repeat_delay / 1000.0;
    } else if (!press && wl.repeat_key == key + 1) {
        wl.repeat_key = 0;
    }
}

static void wl_keyboard_modifiers(void *data, struct wl_keyboard *k, uint32_t serial, uint32_t dep, uint32_t lat, uint32_t lock, uint32_t group)
{
    (void)data; (void)k; (void)serial;
    if (wl.xkb_state) xkb_state_update_mask(wl.xkb_state, dep, lat, lock, 0, 0, group);
}

static void wl_keyboard_repeat_info(void *data, struct wl_keyboard *k, int32_t rate, int32_t delay)
{
    (void)data; (void)k;
    wl.repeat_rate = rate;
    wl.repeat_delay = delay;
}

static const struct wl_keyboard_listener wl_keyboard_listener = {
    wl_keyboard_keymap, wl_keyboard_enter, wl_keyboard_leave, wl_keyboard_key, wl_keyboard_modifiers, wl_keyboard_repeat_info,
};

/* Client-side key repeat at the compositor's rate. */
static void wl_repeat_tick(void)
{
    if (!wl.repeat_key || !wl.keyboard_focus || wl.repeat_rate <= 0) return;
    double now = wl_now();
    for (int n = 0; now >= wl.repeat_next && n < 64; n++) {
        wl_emit_key(wl.keyboard_focus, wl.repeat_key - 1, VIO_REPEAT);
        wl.repeat_next += 1.0 / wl.repeat_rate;
    }
}

/* ── Seat, outputs, registry ──────────────────────────────────────── */

static void wl_seat_capabilities(void *data, struct wl_seat *s, uint32_t caps)
{
    (void)data;
    if ((caps & WL_SEAT_CAPABILITY_POINTER) && !wl.pointer) {
        wl.pointer = wl_seat_get_pointer(s);
        wl_pointer_add_listener(wl.pointer, &wl_pointer_listener, NULL);
    } else if (!(caps & WL_SEAT_CAPABILITY_POINTER) && wl.pointer) {
        wl_pointer_destroy(wl.pointer);
        wl.pointer = NULL;
    }
    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && !wl.keyboard) {
        wl.keyboard = wl_seat_get_keyboard(s);
        wl_keyboard_add_listener(wl.keyboard, &wl_keyboard_listener, NULL);
    } else if (!(caps & WL_SEAT_CAPABILITY_KEYBOARD) && wl.keyboard) {
        wl_keyboard_destroy(wl.keyboard);
        wl.keyboard = NULL;
    }
}

static void wl_seat_name(void *data, struct wl_seat *s, const char *name) { (void)data; (void)s; (void)name; }
static const struct wl_seat_listener wl_seat_listener = { wl_seat_capabilities, wl_seat_name };

static void wl_output_geometry(void *data, struct wl_output *o, int32_t x, int32_t y, int32_t pw, int32_t ph,
                               int32_t subpixel, const char *make, const char *model, int32_t transform)
{
    (void)o; (void)pw; (void)ph; (void)subpixel; (void)transform;
    wl_output_info *oi = (wl_output_info *)data;
    oi->x = x;
    oi->y = y;
    snprintf(oi->name, sizeof(oi->name), "%s %s", make ? make : "", model ? model : "");
}

static void wl_output_mode(void *data, struct wl_output *o, uint32_t flags, int32_t width, int32_t height, int32_t refresh)
{
    (void)o;
    wl_output_info *oi = (wl_output_info *)data;
    if (flags & WL_OUTPUT_MODE_CURRENT) { oi->width = width; oi->height = height; oi->refresh_mhz = refresh; }
    vio_video_mode m = { width, height, (refresh + 500) / 1000, 8, 8, 8 };
    for (int i = 0; i < oi->mode_n; i++) if (memcmp(&oi->modes[i], &m, sizeof(m)) == 0) return;
    if (oi->mode_n < WL_MAX_MODES) oi->modes[oi->mode_n++] = m;
}

static void wl_output_done(void *data, struct wl_output *o) { (void)data; (void)o; }
static void wl_output_scale(void *data, struct wl_output *o, int32_t factor) { (void)o; ((wl_output_info *)data)->scale = factor; }

static const struct wl_output_listener wl_output_listener = { wl_output_geometry, wl_output_mode, wl_output_done, wl_output_scale };

static void wl_registry_global(void *data, struct wl_registry *r, uint32_t id, const char *iface, uint32_t version)
{
    (void)data;
    if (strcmp(iface, wl_compositor_interface.name) == 0) {
        wl.compositor = wl_registry_bind(r, id, &wl_compositor_interface, version < 4 ? version : 4);
    } else if (strcmp(iface, wl_shm_interface.name) == 0) {
        wl.shm = wl_registry_bind(r, id, &wl_shm_interface, 1);
    } else if (strcmp(iface, xdg_wm_base_interface.name) == 0) {
        wl.wm_base = wl_registry_bind(r, id, &xdg_wm_base_interface, 1);
        xdg_wm_base_add_listener(wl.wm_base, &wl_wm_listener, NULL);
    } else if (strcmp(iface, wl_seat_interface.name) == 0 && !wl.seat) {
        wl.seat = wl_registry_bind(r, id, &wl_seat_interface, version < 5 ? version : 5);
        wl_seat_add_listener(wl.seat, &wl_seat_listener, NULL);
    } else if (strcmp(iface, wl_output_interface.name) == 0 && wl.output_n < WL_MAX_OUTPUTS) {
        wl_output_info *oi = &wl.outputs[wl.output_n++];
        memset(oi, 0, sizeof(*oi));
        oi->id = id;
        oi->scale = 1;
        oi->output = wl_registry_bind(r, id, &wl_output_interface, version < 2 ? version : 2);
        wl_output_add_listener(oi->output, &wl_output_listener, oi);
    } else if (strcmp(iface, zxdg_decoration_manager_v1_interface.name) == 0) {
        wl.decoration_manager = wl_registry_bind(r, id, &zxdg_decoration_manager_v1_interface, 1);
    } else if (strcmp(iface, zwp_relative_pointer_manager_v1_interface.name) == 0) {
        wl.relative_manager = wl_registry_bind(r, id, &zwp_relative_pointer_manager_v1_interface, 1);
    } else if (strcmp(iface, zwp_pointer_constraints_v1_interface.name) == 0) {
        wl.constraints = wl_registry_bind(r, id, &zwp_pointer_constraints_v1_interface, 1);
    }
}

static void wl_registry_remove(void *data, struct wl_registry *r, uint32_t id)
{
    (void)data; (void)r;
    for (int i = 0; i < wl.output_n; i++) {
        if (wl.outputs[i].id != id) continue;
        wl_output_destroy(wl.outputs[i].output);
        wl.outputs[i] = wl.outputs[--wl.output_n];
        break;
    }
}

static const struct wl_registry_listener wl_registry_listener = { wl_registry_global, wl_registry_remove };

/* ── Process lifecycle, events ────────────────────────────────────── */

static int wl_init(void)
{
    if (wl.initialized) return 1;
    wl.display = wl_display_connect(NULL);
    if (!wl.display) return 0;
    wl.xkb = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
    wl.registry = wl_display_get_registry(wl.display);
    wl_registry_add_listener(wl.registry, &wl_registry_listener, NULL);
    wl_display_roundtrip(wl.display);   /* globals */
    wl_display_roundtrip(wl.display);   /* seat capabilities, output modes, keymap */
    if (!wl.compositor || !wl.wm_base) {
        php_error_docref(NULL, E_WARNING, "Wayland: the compositor offers no %s", wl.compositor ? "xdg_wm_base" : "wl_compositor");
        wl_display_disconnect(wl.display);
        memset(&wl, 0, sizeof(wl));
        return 0;
    }
    if (wl.shm) {
        const char *size = getenv("XCURSOR_SIZE");
        wl.cursor_theme = wl_cursor_theme_load(getenv("XCURSOR_THEME"), size && atoi(size) > 0 ? atoi(size) : 24, wl.shm);
        if (wl.cursor_theme) {
            wl.cursor = wl_cursor_theme_get_cursor(wl.cursor_theme, "left_ptr");
            if (!wl.cursor) wl.cursor = wl_cursor_theme_get_cursor(wl.cursor_theme, "default");
        }
        wl.cursor_surface = wl_compositor_create_surface(wl.compositor);
    }
    wl.initialized = 1;
    return 1;
}

static void wl_shutdown(void)
{
    if (!wl.initialized) return;
    if (wl.cursor_surface) wl_surface_destroy(wl.cursor_surface);
    if (wl.cursor_theme) wl_cursor_theme_destroy(wl.cursor_theme);
    if (wl.xkb_state) xkb_state_unref(wl.xkb_state);
    if (wl.keymap) xkb_keymap_unref(wl.keymap);
    if (wl.xkb) xkb_context_unref(wl.xkb);
    wl_display_flush(wl.display);
    wl_display_disconnect(wl.display);
    memset(&wl, 0, sizeof(wl));
    wl_egl_display = NULL;
}

/* Read what the compositor sent without blocking (timeout_ms 0), or wait. */
static void wl_dispatch(int timeout_ms)
{
    if (!wl.display) return;
    while (wl_display_prepare_read(wl.display) != 0) wl_display_dispatch_pending(wl.display);
    wl_display_flush(wl.display);
    struct pollfd pfd = { wl_display_get_fd(wl.display), POLLIN, 0 };
    if (poll(&pfd, 1, timeout_ms) > 0 && (pfd.revents & POLLIN)) wl_display_read_events(wl.display);
    else wl_display_cancel_read(wl.display);
    wl_display_dispatch_pending(wl.display);
}

static void wl_poll_events(void)
{
    wl_dispatch(0);
    wl_repeat_tick();
}

static void wl_wait_events(void)
{
    int timeout = -1;
    if (wl.repeat_key) {
        double ms = (wl.repeat_next - wl_now()) * 1000.0;
        timeout = ms > 0 ? (int)ms + 1 : 0;
    }
    wl_dispatch(timeout);
    wl_repeat_tick();
}

/* ── Window lifecycle ─────────────────────────────────────────────── */

static void wl_destroy_window(vio_window_handle h);

static vio_window_handle wl_create_window(vio_config *cfg, const char *backend_name)
{
    if (!wl_init()) {
        php_error_docref(NULL, E_WARNING, "Wayland: cannot connect to \"%s\"", getenv("WAYLAND_DISPLAY") ? getenv("WAYLAND_DISPLAY") : "");
        return NULL;
    }
    vio_wl_window *w = (vio_wl_window *)calloc(1, sizeof(vio_wl_window));
    if (!w) return NULL;
    w->headless = cfg->headless;
    w->decorated = !cfg->headless;
    w->monitor = -1;
    w->scale = 1;
    w->fb_w = w->fb_h = -1;
    w->width  = cfg->width  > 0 ? cfg->width  : 800;
    w->height = cfg->height > 0 ? cfg->height : 600;

    w->surface = wl_compositor_create_surface(wl.compositor);
    wl_surface_set_user_data(w->surface, w);
    wl_surface_add_listener(w->surface, &wl_surface_listener, w);
    w->xdg_surface = xdg_wm_base_get_xdg_surface(wl.wm_base, w->surface);
    xdg_surface_add_listener(w->xdg_surface, &wl_xdg_surface_listener, w);
    w->toplevel = xdg_surface_get_toplevel(w->xdg_surface);
    xdg_toplevel_add_listener(w->toplevel, &wl_toplevel_listener, w);
    xdg_toplevel_set_title(w->toplevel, cfg->title ? cfg->title : "php-vio");
    xdg_toplevel_set_app_id(w->toplevel, "php-vio");
    if (wl.decoration_manager) {
        w->decoration = zxdg_decoration_manager_v1_get_toplevel_decoration(wl.decoration_manager, w->toplevel);
        zxdg_toplevel_decoration_v1_add_listener(w->decoration, &wl_decoration_listener, w);
        zxdg_toplevel_decoration_v1_set_mode(w->decoration, w->decorated ? ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE
                                                                         : ZXDG_TOPLEVEL_DECORATION_V1_MODE_CLIENT_SIDE);
    }
    wl_surface_commit(w->surface);
    for (int i = 0; i < 20 && !w->configured; i++) wl_display_roundtrip(wl.display);
    if (!w->configured) {
        php_error_docref(NULL, E_WARNING, "Wayland: the compositor did not configure the window");
        wl_destroy_window(w);
        return NULL;
    }
    w->width  = cfg->width  > 0 ? cfg->width  : w->width;   /* the request wins over a first configure's size */
    w->height = cfg->height > 0 ? cfg->height : w->height;
    wl_apply_size(w);

    if (backend_name && strcmp(backend_name, "opengl") == 0) {
        int ok = wl_egl_load() && egl.BindAPI(WL_EGL_OPENGL_API);
        void *config = NULL;
        if (ok) {
            ok = 0;
            for (int ms = cfg->samples > 1 ? 1 : 0; ms >= 0 && !ok; ms--) {
                EGLint_ attrs[] = {
                    WL_EGL_SURFACE_TYPE, WL_EGL_WINDOW_BIT, WL_EGL_RENDERABLE_TYPE, WL_EGL_OPENGL_BIT,
                    WL_EGL_RED_SIZE, 8, WL_EGL_GREEN_SIZE, 8, WL_EGL_BLUE_SIZE, 8, WL_EGL_ALPHA_SIZE, 8,
                    WL_EGL_DEPTH_SIZE, 24, WL_EGL_STENCIL_SIZE, 8,
                    WL_EGL_SAMPLE_BUFFERS, ms, WL_EGL_SAMPLES, ms ? cfg->samples : 0,
                    WL_EGL_NONE
                };
                EGLint_ n = 0;
                ok = egl.ChooseConfig(wl_egl_display, attrs, &config, 1, &n) && n > 0;
            }
        }
        if (ok) {
            static const int ladder[][2] = { {4, 6}, {4, 5}, {4, 3}, {4, 1}, {3, 3}, {3, 2}, {3, 1}, {3, 0} };
            for (size_t i = 0; i < sizeof(ladder) / sizeof(ladder[0]) && !w->egl_context; i++) {
                int core = ladder[i][0] * 10 + ladder[i][1] >= 32;
                EGLint_ attrs[] = {
                    WL_EGL_CONTEXT_MAJOR, ladder[i][0], WL_EGL_CONTEXT_MINOR, ladder[i][1],
                    core ? WL_EGL_CONTEXT_PROFILE : WL_EGL_NONE, WL_EGL_CONTEXT_CORE_BIT, WL_EGL_NONE
                };
                w->egl_context = egl.CreateContext(wl_egl_display, config, NULL, attrs);
            }
            ok = w->egl_context != NULL;
        }
        if (ok) {
            w->egl_window = egl.window_create(w->surface, w->width * w->scale, w->height * w->scale);
            w->egl_surface = w->egl_window ? egl.CreateWindowSurface(wl_egl_display, config, w->egl_window, NULL) : NULL;
            ok = w->egl_surface && egl.MakeCurrent(wl_egl_display, w->egl_surface, w->egl_surface, w->egl_context);
        }
        if (ok) {
            /* the floor is 3.0, like GLFW's ladder */
            typedef const unsigned char *(*wl_glGetString_t)(unsigned int);
            wl_glGetString_t gs = (wl_glGetString_t)wl_gl_get_proc_address("glGetString");
            const char *ver = gs ? (const char *)gs(0x1F02) : NULL;
            ok = ver && atoi(ver) >= 3;
        }
        if (!ok) {
            php_error_docref(NULL, E_WARNING, "Wayland: no OpenGL context >= 3.0 available (EGL)");
            wl_destroy_window(w);
            return NULL;
        }
        /* a headless surface may be hidden: never wait for its frame callbacks */
        if (egl.SwapInterval) egl.SwapInterval(wl_egl_display, (cfg->vsync && !cfg->headless) ? 1 : 0);
    }
    wl_display_flush(wl.display);
    return w;
}

static void wl_destroy_window(vio_window_handle h)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (!w) return;
    if (wl.keyboard_focus == w) wl.keyboard_focus = NULL;
    if (wl.pointer_focus == w) wl.pointer_focus = NULL;
    if (w->egl_context) {
        if (egl.GetCurrentContext && egl.GetCurrentContext() == w->egl_context) egl.MakeCurrent(wl_egl_display, NULL, NULL, NULL);
        egl.DestroyContext(wl_egl_display, w->egl_context);
    }
    if (w->egl_surface) egl.DestroySurface(wl_egl_display, w->egl_surface);
    if (w->egl_window) egl.window_destroy(w->egl_window);
    if (w->relative) zwp_relative_pointer_v1_destroy(w->relative);
    if (w->locked) zwp_locked_pointer_v1_destroy(w->locked);
    if (w->decoration) zxdg_toplevel_decoration_v1_destroy(w->decoration);
    if (w->toplevel) xdg_toplevel_destroy(w->toplevel);
    if (w->xdg_surface) xdg_surface_destroy(w->xdg_surface);
    if (w->surface) wl_surface_destroy(w->surface);
    if (wl.display) wl_display_flush(wl.display);
    free(w);
}

static int  wl_should_close(vio_window_handle h) { return h ? ((vio_wl_window *)h)->should_close : 1; }
static void wl_set_should_close(vio_window_handle h, int v) { if (h) ((vio_wl_window *)h)->should_close = v; }

static void wl_swap_buffers(vio_window_handle h)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (w && w->egl_surface) egl.SwapBuffers(wl_egl_display, w->egl_surface);
}

static void wl_get_framebuffer_size(vio_window_handle h, int *fw, int *fh)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (fw) *fw = w ? w->width * w->scale : 0;
    if (fh) *fh = w ? w->height * w->scale : 0;
}

static void wl_get_window_size(vio_window_handle h, int *ww, int *wh)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (ww) *ww = w ? w->width : 0;
    if (wh) *wh = w ? w->height : 0;
}

static void wl_get_content_scale(vio_window_handle h, float *sx, float *sy)
{
    vio_wl_window *w = (vio_wl_window *)h;
    float s = w ? (float)w->scale : 1.0f;
    if (sx) *sx = s;
    if (sy) *sy = s;
}

static void wl_get_cursor_pos(vio_window_handle h, double *x, double *y)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (x) *x = w ? w->cursor_x : 0.0;
    if (y) *y = w ? w->cursor_y : 0.0;
}

static int wl_gl_make_current(vio_window_handle h)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (!wl_egl_display) return -1;
    if (!w) return egl.MakeCurrent(wl_egl_display, NULL, NULL, NULL) ? 0 : -1;
    return egl.MakeCurrent(wl_egl_display, w->egl_surface, w->egl_surface, w->egl_context) ? 0 : -1;
}

static void wl_gl_swap_interval(int interval)
{
    if (wl_egl_display && egl.SwapInterval) egl.SwapInterval(wl_egl_display, interval);
}

/* ── Window properties ────────────────────────────────────────────── */

static void wl_set_title(vio_window_handle h, const char *utf8)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (w && utf8) { xdg_toplevel_set_title(w->toplevel, utf8); wl_display_flush(wl.display); }
}

/* Outside fullscreen / maximised the client picks its size. */
static void wl_set_window_size(vio_window_handle h, int ww, int wh)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (!w || w->monitor >= 0 || ww <= 0 || wh <= 0) return;
    w->width = ww;
    w->height = wh;
    wl_apply_size(w);
}

static void wl_get_window_pos(vio_window_handle h, int *x, int *y)
{
    (void)h;   /* Wayland clients cannot know their position */
    if (x) *x = 0;
    if (y) *y = 0;
}

static void wl_set_window_pos(vio_window_handle h, int x, int y) { (void)h; (void)x; (void)y; }

static int wl_get_attrib(vio_window_handle h, vio_window_attrib a)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (!w) return 0;
    switch (a) {
        case VIO_WINDOW_DECORATED:    return w->decorated;
        case VIO_WINDOW_MAXIMIZED:    return w->maximized;
        case VIO_WINDOW_AUTO_ICONIFY: return w->auto_iconify;
        case VIO_WINDOW_FOCUSED:      return wl.keyboard_focus == w;
        case VIO_WINDOW_VISIBLE:      return 1;
    }
    return 0;
}

static void wl_set_attrib(vio_window_handle h, vio_window_attrib a, int value)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (!w) return;
    switch (a) {
        case VIO_WINDOW_DECORATED:
            w->decorated = value ? 1 : 0;
            if (w->decoration) {
                zxdg_toplevel_decoration_v1_set_mode(w->decoration, w->decorated ? ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE
                                                                                 : ZXDG_TOPLEVEL_DECORATION_V1_MODE_CLIENT_SIDE);
            }
            break;
        case VIO_WINDOW_AUTO_ICONIFY:
            w->auto_iconify = value ? 1 : 0;
            break;
        default:
            break;
    }
    wl_display_flush(wl.display);
}

static void wl_maximize(vio_window_handle h)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (w) { xdg_toplevel_set_maximized(w->toplevel); wl_display_flush(wl.display); }
}

static void wl_restore(vio_window_handle h)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (w) { xdg_toplevel_unset_maximized(w->toplevel); wl_display_flush(wl.display); }
}

static void wl_set_cursor_mode(vio_window_handle h, int mode)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (!w || w->cursor_mode == mode) return;
    if (w->cursor_mode == VIO_PLATFORM_CURSOR_DISABLED) {
        if (w->locked) { zwp_locked_pointer_v1_destroy(w->locked); w->locked = NULL; }
        if (w->relative) { zwp_relative_pointer_v1_destroy(w->relative); w->relative = NULL; }
    }
    w->cursor_mode = mode;
    if (mode == VIO_PLATFORM_CURSOR_DISABLED && wl.pointer) {
        if (wl.constraints) {
            w->locked = zwp_pointer_constraints_v1_lock_pointer(wl.constraints, w->surface, wl.pointer, NULL,
                                                                ZWP_POINTER_CONSTRAINTS_V1_LIFETIME_PERSISTENT);
            zwp_locked_pointer_v1_add_listener(w->locked, &wl_locked_listener, w);
        }
        if (wl.relative_manager) {
            w->relative = zwp_relative_pointer_manager_v1_get_relative_pointer(wl.relative_manager, wl.pointer);
            zwp_relative_pointer_v1_add_listener(w->relative, &wl_relative_listener, w);
        }
    }
    if (wl.pointer_focus == w) wl_set_cursor(w);
    wl_display_flush(wl.display);
}

static int wl_window_monitor(vio_window_handle h)
{
    return h ? ((vio_wl_window *)h)->monitor : -1;
}

/* Fullscreen on an output: the compositor scales, there is no mode switch. */
static void wl_set_window_monitor(vio_window_handle h, int monitor, int x, int y, int width, int height, int refresh_hz)
{
    (void)x; (void)y; (void)refresh_hz;
    vio_wl_window *w = (vio_wl_window *)h;
    if (!w) return;
    if (monitor >= 0) {
        if (monitor >= wl.output_n) monitor = 0;
        w->monitor = monitor;
        xdg_toplevel_set_fullscreen(w->toplevel, wl.output_n ? wl.outputs[monitor].output : NULL);
    } else {
        w->monitor = -1;
        xdg_toplevel_unset_fullscreen(w->toplevel);
        if (width > 0 && height > 0) { w->width = width; w->height = height; }
    }
    wl_display_roundtrip(wl.display);
    wl_apply_size(w);
}

/* ── Monitors ─────────────────────────────────────────────────────── */

static int wl_monitor_count(void)
{
    return wl_init() ? wl.output_n : 0;
}

static int wl_primary_monitor(void)
{
    return wl_monitor_count() > 0 ? 0 : -1;   /* Wayland has no primary output: the first one */
}

static int wl_monitor_desc(int index, vio_monitor_desc *out)
{
    memset(out, 0, sizeof(*out));
    if (!wl_init() || index < 0 || index >= wl.output_n) return -1;
    wl_output_info *oi = &wl.outputs[index];
    const char *n = oi->name;
    while (*n == ' ') n++;
    snprintf(out->name, sizeof(out->name), "%s", *n ? n : "Wayland output");
    out->x = oi->x;
    out->y = oi->y;
    int s = oi->scale > 0 ? oi->scale : 1;
    out->work_x = oi->x;
    out->work_y = oi->y;
    out->work_width = oi->width / s;
    out->work_height = oi->height / s;
    out->scale_x = out->scale_y = (float)s;
    out->mode.width = oi->width;
    out->mode.height = oi->height;
    out->mode.refresh_hz = (oi->refresh_mhz + 500) / 1000;
    out->mode.red_bits = out->mode.green_bits = out->mode.blue_bits = 8;
    out->primary = index == 0;
    return 0;
}

static int wl_mode_cmp(const void *a, const void *b)
{
    const vio_video_mode *x = (const vio_video_mode *)a, *y = (const vio_video_mode *)b;
    long ax = (long)x->width * x->height, ay = (long)y->width * y->height;
    if (ax != ay) return ax < ay ? -1 : 1;
    if (x->width != y->width) return x->width - y->width;
    return x->refresh_hz - y->refresh_hz;
}

static int wl_video_modes(int index, vio_video_mode *out, int max)
{
    if (!wl_init() || index < 0 || index >= wl.output_n || max <= 0) return 0;
    wl_output_info *oi = &wl.outputs[index];
    int n = 0;
    for (int i = 0; i < oi->mode_n && n < max; i++) out[n++] = oi->modes[i];
    qsort(out, (size_t)n, sizeof(out[0]), wl_mode_cmp);
    return n;
}

/* ── Native handles, Vulkan, input ────────────────────────────────── */

static void *wl_native_handle(vio_window_handle h, vio_native_kind kind)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (!w) return NULL;
    if (kind == VIO_NATIVE_WAYLAND_SURFACE) return w->surface;
    if (kind == VIO_NATIVE_WAYLAND_DISPLAY) return wl.display;
    return NULL;
}

#ifdef HAVE_VULKAN
static const char **wl_vk_instance_extensions(uint32_t *count)
{
    static const char *ext[] = { "VK_KHR_surface", "VK_KHR_wayland_surface" };
    *count = 2;
    return ext;
}

static int wl_vk_create_surface(vio_window_handle h, void *instance, void *out_surface)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (!w) return (int)VK_ERROR_INITIALIZATION_FAILED;
    VkWaylandSurfaceCreateInfoKHR ci;
    memset(&ci, 0, sizeof(ci));
    ci.sType = VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR;
    ci.display = wl.display;
    ci.surface = w->surface;
    return (int)vkCreateWaylandSurfaceKHR((VkInstance)instance, &ci, NULL, (VkSurfaceKHR *)out_surface);
}
#endif

static void wl_install_input(vio_window_handle h, vio_input_state *state)
{
    vio_wl_window *w = (vio_wl_window *)h;
    if (w) w->input = state;
}

static const vio_platform vio_platform_wayland = {
    .name                 = "wayland",
    .init                 = wl_init,
    .shutdown             = wl_shutdown,
    .create_window        = wl_create_window,
    .destroy_window       = wl_destroy_window,
    .should_close         = wl_should_close,
    .set_should_close     = wl_set_should_close,
    .poll_events          = wl_poll_events,
    .wait_events          = wl_wait_events,
    .swap_buffers         = wl_swap_buffers,
    .get_framebuffer_size = wl_get_framebuffer_size,
    .get_window_size      = wl_get_window_size,
    .get_content_scale    = wl_get_content_scale,
    .get_cursor_pos       = wl_get_cursor_pos,
    .gl_make_current      = wl_gl_make_current,
    .gl_swap_interval     = wl_gl_swap_interval,
    .gl_get_proc_address  = wl_gl_get_proc_address,
    .set_title            = wl_set_title,
    .set_window_size      = wl_set_window_size,
    .get_window_pos       = wl_get_window_pos,
    .set_window_pos       = wl_set_window_pos,
    .get_attrib           = wl_get_attrib,
    .set_attrib           = wl_set_attrib,
    .maximize             = wl_maximize,
    .restore              = wl_restore,
    .set_cursor_mode      = wl_set_cursor_mode,
    .window_monitor       = wl_window_monitor,
    .set_window_monitor   = wl_set_window_monitor,
    .monitor_count        = wl_monitor_count,
    .primary_monitor      = wl_primary_monitor,
    .monitor_desc         = wl_monitor_desc,
    .video_modes          = wl_video_modes,
    .joystick_present     = evdev_joystick_present,
    .joystick_is_gamepad  = evdev_joystick_present,
    .joystick_name        = evdev_pad_name,
    .gamepad_name         = evdev_pad_name,
    .gamepad_state        = evdev_gamepad_state,
    .joystick_buttons     = evdev_joystick_buttons,
    .joystick_axes        = evdev_joystick_axes,
    .native_handle        = wl_native_handle,
#ifdef HAVE_VULKAN
    .vk_instance_extensions = wl_vk_instance_extensions,
    .vk_create_surface      = wl_vk_create_surface,
#endif
    .install_input        = wl_install_input,
};

void vio_platform_wayland_register(void)
{
    vio_register_platform(&vio_platform_wayland);
}

#endif /* HAVE_WAYLAND */
